version: '3.8'

services:
  ubuntu-dev:
    build: .
    container_name: debian:macos
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  data:
    driver: local
